CREATE SEQUENCE CLIENTE_SEQ START WITH 7 INCREMENT BY 1;

CREATE TABLE CLIENTE(
	ID INTEGER NOT NULL, 
	NOME VARCHAR, 
	PLANO_EXCLUSIVE BOOLEAN, 
	NUMERO_CONTA VARCHAR,
	DATA_NASCIMENTO DATE,
	SALDO NUMERIC,
	PRIMARY KEY (ID));