CREATE SEQUENCE CLIENTE_SEQ START WITH 7 INCREMENT BY 1;
CREATE SEQUENCE TRANSACAO_SEQ START WITH 9 INCREMENT BY 1;

CREATE TABLE CLIENTE(
	ID INTEGER NOT NULL, 
	NOME VARCHAR, 
	PLANO_EXCLUSIVE BOOLEAN, 
	NUMERO_CONTA VARCHAR,
	DATA_NASCIMENTO DATE,
	SALDO NUMERIC,
	PRIMARY KEY (ID));
	
CREATE TABLE TRANSACAO(
	ID INTEGER NOT NULL,
	DATA DATE,
	VALOR NUMERIC,
	TIPO VARCHAR(10),
	CLIENTE_ID INTEGER,
	PRIMARY KEY (ID)
);

ALTER TABLE TRANSACAO
ADD FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID);